# Generated by Django 2.2.5 on 2019-10-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_vehiculo_anyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichas.Cliente', verbose_name='Dueño'),
        ),
    ]
