# Generated by Django 2.2.5 on 2019-10-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20191007_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
