# Generated by Django 2.2.5 on 2019-10-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_vehiculo_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
