# Generated by Django 2.2.5 on 2019-10-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_auto_20191014_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(default='Sedán', max_length=40),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='observaciones',
            field=models.CharField(max_length=500),
        ),
    ]
