# Generated by Django 2.2.5 on 2019-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_auto_20191014_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='pin',
            field=models.CharField(default=3865, max_length=4),
        ),
    ]
