# Generated by Django 2.2.5 on 2019-11-04 18:46

from django.db import migrations, models
import fichas.models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_atencion_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='pin',
            field=models.CharField(default=fichas.models.create_pin, max_length=4),
        ),
    ]
