# Generated by Django 2.2.5 on 2019-11-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_auto_20191104_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
