# Generated by Django 2.2.5 on 2019-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_atencion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
