# Generated by Django 2.2.5 on 2019-11-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0014_auto_20191109_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
