# Generated by Django 2.2.5 on 2019-11-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0016_searchquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='id_detalle',
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
        migrations.AddField(
            model_name='detalle',
            name='repuesto',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='detalle',
            name='valor_repuesto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='observaciones',
            field=models.CharField(max_length=512),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
