# Generated by Django 2.2.5 on 2019-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0017_auto_20191109_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
