# Generated by Django 2.2.5 on 2019-12-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0005_auto_20191212_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='observaciones',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
