# Generated by Django 2.2.5 on 2019-12-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0006_hora_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
