# Generated by Django 2.2.5 on 2019-12-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0007_hora_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
